### ISSUE TITLE
Meta issue: support `return`/`continue`/`?`/`break` 

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#15]
This issue is about any expression that can yield an early return: `?`, `return`, `continue`, `break`.

The engine has a module `side_effect_utils.ml` that deals with any expression with side effects: its approach is to hoist every side effect within an expression.

After applying this side effect phase, expressions are trees with `let`, `if`, `match`, `loop` nodes, and the side-effects occur only on rhs of `let`s.

Note early return is one of the different possible side effects. Also, one cannot rewrite early returns without considering other side effects: for instance, early returns can interact badly with mutation.

From there:
 - [`CfIntoMonads`](https://github.com/hacspec/hax/blob/main/engine/lib/phases/phase_cf_into_monads.ml) lifts early return bottom up into various monads.
 - we also want a phase that attempts to restructure control flow, to push early returns to end positions.

### Road map
 - [x] resugar questions marks (Rustc rewrite `?` with `return`s);
 - [x] add a phase that transforms early returns into monadic constructions;
     + [ ] test this monadic phase;
     + [ ] fix bugs; 
 - [x] add a phase that attempts at reformulating control flow to avoid early returns (i.e. we'd better do `if c {return e1} return e2` -> `return (if c {e1} {e2})` than a monadic transformation) (see #393 and #254);
 - [ ] wrap the monadic and reformulation phase into another phase that decides heuristically which looks best.
 - [ ] support continue/return within loops: #196

# Original issue
> This is related to the question mark operator, since `e?` actually expands to a `match` whose one branch is a `return` statement.
> 
> TODOs:
> - (x) add a phase that transforms early returns into monadic constructions;
> -  fix the current monadic encoding #399;
> -  add a phase that attempts at reformulating control flow to avoid early returns (i.e. we'd better do `if c {return e1} return e2` -> `return (if c {e1} {e2})` than a monadic transformation) (see #393);
> -  add a phase that tries both monadic and control-flow reformulation phases and decides heuristically which seems better;
> - (x) figure out how to translate code containing the `?` operator nicely (some resugaring?).

**Comment by W95Psp** [comment]
Yes, you are right, hax should already handle basic rewriting when it's possible.
I'm gonna try to allocate some time to that somewhere next week!

**Comment by W95Psp** [comment]
Fixed by #988

**Comment by W95Psp** [comment]
This is closed, the regression is tracked by https://github.com/hacspec/hax/issues/1044, and is going to be fixed soon.
