### ISSUE TITLE
[Meta] ProVerif backend tracking issue

### ISSUE THREAD

**Issue by jschneider-bensch** [hacspec/hax#382]
This issue collects sub-tasks for the ProVerif backend.

- [ ] Extract ProVerif process macros from Rust `fn`s
- [ ] Extract ProVerif processes from annotated Rust `fn`s
- [ ] `hax-pv-lib` Rust component (this let's us define top-level processes)
   - [ ] Protocol runtime
- [ ] `hax-pv-lib` ProVerif component (this let's us translate known API calls)
  - [ ]  function definitions for `libcrux` APIs
  - [ ] state management facilities

**Comment by jschneider-bensch** [comment]
Tracking the more specific issues for the current milestone (Extracting the Bertie TLS handshake) in #541.
