### ISSUE TITLE
Libraries for abstractions enforcing invariants 

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#431]
Rust is a quite powerful language and can help to enforce invariants.

Each invariant or property one can enforce in Rust already is something we don't need to write and maintain a proof for.
This issue lists the supporting Rust libraries we want to enforce common invariants.

 - **Computationally relevant code**
    - [x] bounded integers: [newtype](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) that wraps primitive Rust integers (e.g. `u8`, `i32`, `isize`...) but representing integers that are restricted to explicit and type-specified bounds. Those wrappers should `assert!` their inhabitant are within bounds in debug mode. In release mode, those wrappers should be zero-cost abstractions.
    - [x] safe indexing: newtype that wraps arrays and provides safe indexes, i.e. indexes that can be used in a never-panicking way to index a structure.
    - [ ] secret independence: interesting article https://lukas-prokop.at/articles/2022-05-05-secret-types-for-rust
 - **Specification (ghost) code**
    - [x] abstract integers: a set of mathematical (both bounded and unbounded) integers, useful for specifications.
    - [ ] sequences: abstraction of arrays or slices.

**Comment by W95Psp** [comment]
I think this is still relevant, and connected to what @cmester0 is doing with libcore
