### ISSUE TITLE
Introduce ghost traits

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#544]
Rust doesn't track panics or divergence in its type system.

For inherent implementations or simple function definitions, this is not a problem: we can always decorate them with pre- and post-conditions or similar.

For traits, however, things get more complicated. Annotating an `impl` method is useless: it will be exposed with the signature defined in the trait.

One possibility is to turn those annotations into trait methods that impose pre and post-conditions to impls. This is not OK in the settings of a trait from an external crate.

## Solution
Instead, for every trait `T`, we should be able to define a trait `T_ghost`.
For each method `f: T1 -> ... -> TN -> O` (assuming no `&mut`) in `T`, `T_ghost` should contain:
 - `f_pre: T1 -> ... -> TN -> bool`;
 - `f_post: T1 -> ... -> TN -> O -> bool`;
 - `f_decreases: T1 -> ... -> TN -> ANY` a decreases clause (though this is very F* specific).
For each type  `U` in `T`, `T_ghost` should (probably?) contain `U_refinement: U -> bool`.

### Definition of the trait `T_ghost`
Should be right after or before the definition of `T`, otherwise, we need to refer to it explicitly when defining impls.

### Impl blocks of `T_ghost`
The design should allow for inexistent `T_ghost` impls: sometimes, an implementation of trait `T` for a type is total and requires no annotation.

We need a way of connecting `impl` blocks for `T` and `impl` blocks for `T_ghost` very tightly: we don't want to ask the rust compiler for the trait resolution of both `T` and `T_ghost`.
An impl of `T` should correspond exactly to zero or one impl of `T_ghost` for the exact same type.

Instead, I think we should impose the following principle: if one wants to extract a `T` impl block with pre/postconditions/refinements/whatever, one should associate it with one `T_ghost` impl block.

`T_ghost` impls should be marked with an attribute (say `is_ghost_trait`) and should have a parent clause to `T`. This parent clause to `T` should resolve exactly to a concrete impl block. This way, whenever hax sees a `is_ghost_trait` impl, it finds it's `T` parent clause and links it automatically.

### Parent traits in the extractions
We should reverse the parent-child relation between `T` and `T_ghost` in the extraction. In Rust, we cannot have `T_ghost` a parent of `T`, otherwise the pattern would not work for external traits. In the extraction, we should always be able to grab pre/posts given a impl of `T`.

## Ergonomics
Users should (almost) never write `T_ghost` trait definition or impls. Instead, they should annotate traits methods and type.
## Roadmap
 - [ ] add an `is_ghost` attribute in hax
 - [ ] generate `*_ghost` traits
 - [ ] edit the macros so that one can annotate an impl block with pre/post/...
        (Note that default methods in `T` should be default as well in `T_ghost`, inheriting annotations)

**Comment by W95Psp** [comment]
Note: we want to get a minimal support for this ASAP.

Minimal means have the full mechanism, but without any sugar (if you want a precondition, then you'll have to write everything manually)
