### ISSUE TITLE
[META] Engine: enhancements to the concrete ident view API

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#973]
As pointed out by @paulmure in #793, the current view API for concrete ident is limited.
As discussed there, we might either (1) expose the raw types as #793 suggests or (2) build a more expressive API.

I'm in favor of (2) because:
 - the representation of concrete idents in the engine is complex: it's basically rustc `DefId`s + a kind we compute in import_thir
 - there are invariants on those concrete idents, I'd like them to be contained in this module
 - the view API exists because I want to ensure monolithically that we don't produce a same backend identifier for two different Rust identifiers.

The danger of (2) is to end up with a complex and messy view API.

The purpose of this issue is to describe the various missing functionality of this view API, and to track refactoring work to make it more modular.

## Expressiveness: name policy
 - [x] reserved words: a list of keywords that should be escaped (valid identifiers in Rust are not always valid in the target backend)
 - [x] transform numeric fields on structs: tuple structs can be accessed via e.g. `x.1` in Rust, sometimes not in the backend, so we need to rename
 - [ ] control prefixes added by the name API (as suggested by @paulmure in #793). We currently hardcode many rules, e.g. rename constructor that begins with anything else but an uppercase Latin letter. We should be able to configure those rules: what prefix is added, when.
 - [ ] control how much of the fully qualified path is used based on what’s currently imported (quoting @paulmure)
 - Please comment if you think about something here!

**Comment by W95Psp** [comment]
Still relevant, and related to #1135.

**Comment by karthikbhargavan** [comment]
Revisit this when defining the Rust AST.

**Comment by maximebuyse** [comment]
This issue is specific to the OCaml engine so it will be fixed by the new engine.
